### ISSUE TITLE
Time-out on clean-up of languages and platform updates

### ISSUE THREAD

**Issue by tankerkiller125** [ralish/PSWsusSpringClean#1]
I've successfully run the built-in cleanup tool and I've also successfully run a reindex operation. However when I attempt to use this tool to cleanup languages and platform-specific updates PowerShell times out. I've tried finding instructions to extend this timeout but no matter what I do it seems that the script times out after about 5 minutes. Is there something I'm missing?

I should note that it crashes at the "Retrieving approved updates" stage of the cleanup.

**Comment by ralish** [comment]
I've run into this problem myself in various scenarios. Unfortunately, the timeout is not controlled by _PSWsusSpringClean_ but seems to be set within the WSUS .NET library itself, and does not appear to be configurable. For memory it's actually the SQL query timeout.

The underlying code that is being run at the point you reference follows:
```
$WsusServer = Get-WsusServer
$UpdateScope = New-Object -TypeName Microsoft.UpdateServices.Administration.UpdateScope
$UpdateScope.ApprovedStates = [Microsoft.UpdateServices.Administration.ApprovedStates]::LatestRevisionApproved
$WsusApproved = $WsusServer.GetUpdates($UpdateScope)
```

If you run the above snippet in an elevated PowerShell session do you see the same timeout after the final line? You mention performing a re-index operation; are you referring to [this script](https://gallery.technet.microsoft.com/scriptcenter/Optimize-and-cleanup-of-eb9d8640) or something else?

**Comment by tankerkiller125** [comment]
Unfortunately, I haven't gotten a chance to test the code you provided yet, however, if it is the WSUS application itself it might be possible to change the timeout by changing the application pool settings in IIS. I'll have to take a deeper look tomorrow at work.

**Comment by tankerkiller125** [comment]
@ralish Ok so, I can confirm that it timeouts after that last line, and yes the reindex operation is part of that script you linked too. I also tried increasing the WSUS pool timeout but that had no effect. Are there any solutions for this?

**Comment by ralish** [comment]
Not that I know of, but we can try and find one. Can we start with a few details about your setup?

WSUS OS version (e.g. Windows Server 2012 R2)
SQL Server version (e.g. Windows Internal Database or SQL Server 2014)
WSUS database size
No. of approved updates

For the database size you can just check the `SUSDB.mdf` (database) and `SUSDB.ldf` (log) as a quick and dirty method if using WID. If using a full SQL Server installation use SMSS or your preferred management tool.

For what it's worth the referenced commands are very fast for me. On a WSUS server with 1107 approved updates retrieving the approved updates takes less than a second.

**Comment by tankerkiller125** [comment]
WSUS OS: Windows server 2016
SQL Version: WID
WSUS Database Size: 9.7MB
Approved Updates: Somewhere between 50K and 70K (Previous admin allowed all updates except for Upgrades, he included all categories and products, I've been working on cleaning that up)

**Comment by ralish** [comment]
With that many updates and a WID server your problem is definitely going to be the database itself (and there's no way it's 9.7MB!). Queries on the database are timing out when invoked by this module, and I'd be surprised if you weren't seeing timeouts on other utilities that interact with WSUS?

Bluntly, the default WSUS database leaves a lot to be desired w.r.t. handling the large volumes of update metadata, with simple things like sensible indexes missing and periodic database maintenance left up to the admin. You've already done the basics by the sound of it per the earlier linked script, but clearly that isn't enough in this case to get the database sufficiently responsive.

You might want to take a look at this MS blog post if you haven't already:
[The complete guide to Microsoft WSUS and Configuration Manager SUP maintenance](https://blogs.technet.microsoft.com/configurationmgr/2016/01/26/the-complete-guide-to-microsoft-wsus-and-configuration-manager-sup-maintenance/)

Beyond that, something like [WSUS Automated Maintenance](https://www.ajtek.ca/) might be worth a look. I haven't personally used it, but it gets a good reception on various forums and was previously a free script on Spiceworks.

The problem you have is really out-of-scope of what this module seeks to address. The intent of this module is to clean-up unwanted updates but it assumes the underlying database itself is sufficiently healthy and responsive. Have a look at the above linked resources and hopefully that'll help you get your WSUS database into a state where this module can then help with declining all the unwanted updates so your database remains healthy.

Feel free to let me know how you go, particularly if you end up using WSUS Automated Maintenance :)

**Comment by tankerkiller125** [comment]
@ralish I'm running a database based cleanup tool this weekend, it's pretty slow but based on my reading it appears to work pretty well and its open source. The only problem I have so far with it is that it tries to execute a WSUS cleanup via PowerShell (which of course fails) but the actual database part seems to work really well.
